# Generated by Django 2.2.6 on 2020-08-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pedido realizado"),
                            ("F", "Fazendo"),
                            ("E", "Saiu para entrega"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destino",
                        to="enderecos.Endereco",
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(
                        related_name="carrinho", to="produtos.Produto"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
