# Generated by Django 2.2.6 on 2020-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0003_auto_20200807_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
